### ISSUE TITLE
Error: element.click is not a function

### ISSUE THREAD

**Issue by roachfr** [XternA/cryptos-faucets-bot#2]
signup fails because of this error, also the main bot has the same error.
running on windows 10, all modules are installed
https://prnt.sc/107tnkp

**Comment by XternA** [comment]
I've not had the same issue as you, nor able to reproduce it. It's working for me with the exception that the `waitForNaviation()` delay causes Puppeteer to timeout. This is only in the signup bot. Main bot works as expected.

I've made some small changes to the code so I suggest you pull the new changes first.

I'd suggest using the latest version of Node.js (What I'm currently using), not the LTS version. Remove the `node_modules` directory completely with `rd /q/s node_modules` and attempt to install the modules again.

**Comment by roachfr** [comment]
yes, i was able to fix it by reinstalling node. thanks for the help.
one more question,do you have a rough estimate of the daily revenue generated by the bot.

**Comment by XternA** [comment]
You can easily work it out, multiply the satoshi by 24 and that should give you a rough estimation. Of course, if you factor in the promo codes, your estimates could vary. The whole point is to run it as long as possible as a lot of the coins are a store of value at the moment. The real value comes to play couple years down the line so HODL.
